version: '3.8'

services:
  nginx:
    image: nginx:1.25
    container_name: nginx_auth
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
    depends_on:
      - backend

  backend:
    container_name: backend_service
    build: ./backend
    ports:
      - "8081:3000"  # Nếu NodeJS (hoặc đổi thành 8081:8080 nếu Spring Boot)
